apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  type: ClusterIP
  selector:
    app: boardgame
  ports:
    - name: http #For prometheus
      port: 80
      targetPort: 8080
